
message(STATUS "${CONAN_LIB_DIRS_LIBEVENT}")

find_path(LIBEVENT_INCLUDE_DIR NAMES LIBEVENT.h PATHS ${CONAN_INCLUDE_DIRS_LIBEVENT})
find_library(LIBEVENT_LIBRARY NAMES ${CONAN_LIBS_LIBEVENT} PATHS ${CONAN_LIB_DIRS_LIBEVENT})

set(LIBEVENT_INCLUDE_DIRS ${LIBEVENT_INCLUDE_DIR})
set(LIBEVENT_LIBRARIES ${LIBEVENT_LIBRARY} ${EXTRA_LIBS})

mark_as_advanced(LIBEVENT_LIBRARY LIBEVENT_INCLUDE_DIR)

message("** LIBEVENT found by Conan!")
set(LIBEVENT_FOUND TRUE)
message("   - libraries:  ${LIBEVENT_LIBRARIES}")
message("   - includes:  ${LIBEVENT_INCLUDE_DIRS}")

